# vim:ft=kitty

## name:     Kanagawa Paper Ink
## upstream: https://github.com/thesimonho/kanagawa-paper.nvim

foreground              #DCD7BA
background              #1F1F28
selection_foreground    #C8C093
selection_background    #2D4F67

cursor                  #C8C093
cursor_text_color       #1F1F28

url_color               #7E9CD8

active_border_color     #7E9CD8
inactive_border_color   #54546D
bell_border_color       #FF9E3B

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #1F1F28
active_tab_background   #7E9CD8
inactive_tab_foreground #727169
inactive_tab_background #1F1F28
tab_bar_background      #16161D

mark1_foreground #1F1F28
mark1_background #7E9CD8
mark2_foreground #1F1F28
mark2_background #957FB8
mark3_foreground #1F1F28
mark3_background #76946A

# black
color0  #16161D
color8  #727169

# red
color1  #C34043
color9  #E82424

# green
color2  #76946A
color10 #98BB6C

# yellow
color3  #C0A36E
color11 #E6C384

# blue
color4  #7E9CD8
color12 #7FB4CA

# magenta
color5  #957FB8
color13 #938AA9

# cyan
color6  #6A9589
color14 #7AA89F

# white
color7  #C8C093
color15 #DCD7BA
