# Kanagawa Paper Ink theme
gui:
  theme:
    activeBorderColor:
      - "#8992A7"
      - bold
    inactiveBorderColor:
      - "#54546D"
    optionsTextColor:
      - "#859FAC"
    selectedLineBgColor:
      - "#363646"
    selectedRangeBgColor:
      - "#2A2A37"
    cherryPickedCommitBgColor:
      - "#2A2A37"
    cherryPickedCommitFgColor:
      - "#C4B28A"
    unstagedChangesColor:
      - "#C4746E"
    defaultFgColor:
      - "#DCD7BA"
    searchingActiveBorderColor:
      - "#E6C384"
  authorColors:
    "*": "#A292A3"
  nerdFontsVersion: "3"
