"$schema" = 'https://starship.rs/config-schema.json'
add_newline = false

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "bold #949fb5"

[character]
success_symbol = "[❯](#8992a7)"
error_symbol = "[❯](#c4746e)"
vimcmd_symbol = "[❮](#8a9a7b)"

[git_branch]
format = "[$branch]($style)"
style = "#c4b28a"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](#b6927b) ($ahead_behind$stashed)]($style)"
style = "#859fac"
conflicted = ""
untracked = ""
modified = ""
staged = ""
renamed = ""
deleted = ""
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#8ea49e"

[cmd_duration]
format = "[$duration]($style) "
style = "#b6927b"

[python]
format = "[$virtualenv]($style) "
style = "#8a9a7b"
detect_extensions = []
detect_files = []
