#!/usr/bin/env bash
# Set every out/<App>.icns (generated by recolor.py) plus the hand-drawn icons
# below as the custom icon of /Applications/<App>.app.
# App updates replace the bundle and drop the icon, so topgrade reruns this.
# Undo one app: fileicon rm "/Applications/<App>.app"
set -euo pipefail

dir="$(cd "$(dirname "$0")" && pwd)"

# Hand-drawn icons that recolor.py should not touch.
handmade=(
  "$dir/../ghostty/icon/Ghostty.icns"
)

# Root-owned apps need sudo. Without a terminal to prompt in (topgrade, scripts)
# sudo -n fails fast and those apps are listed as skipped instead of hanging.
if [[ -t 0 ]]; then as_root=(sudo); else as_root=(sudo -n); fi

skipped=()
for icns in "$dir"/out/*.icns "${handmade[@]}"; do
  app="/Applications/$(basename "$icns" .icns).app"
  [[ -d "$app" ]] || { echo "skip: $app not installed"; continue; }
  if [[ -w "$app" ]]; then
    run=()
  else
    run=("${as_root[@]}")
  fi
  # App Store apps can refuse even root (App Management protection); keep going.
  if ! "${run[@]}" fileicon set "$app" "$icns" >/dev/null 2>&1; then
    skipped+=("$app")
    continue
  fi
  # A new mtime invalidates the IconServices cache entry, so the Dock re-reads it.
  "${run[@]}" touch "$app"
  echo "set: $app"
done

if ((${#skipped[@]})); then
  printf 'skipped (needs sudo in a terminal, or macOS blocked it):\n'
  printf '  %s\n' "${skipped[@]}"
fi

# The Dock keeps its own icon cache for pinned apps; drop it so they refresh.
/bin/rm -f "$(getconf DARWIN_USER_CACHE_DIR)com.apple.dock.iconcache"
killall Dock Finder 2>/dev/null || true
