[[themes]]
name = "kanagawa-paper-ink"

[themes.palette]
background = "#1F1F28"
foreground = "#DCD7BA"
black = "#393836"
blue = "#435965"
cyan = "#8EA49E"
green = "#699469"
magenta = "#A292A3"
red = "#C4746E"
white = "#C8C093"
yellow = "#C4B28A"
bright_black = "#ACA9A4"
bright_blue = "#698A9B"
bright_cyan = "#96ADA7"
bright_green = "#72A072"
bright_magenta = "#B4A7B5"
bright_red = "#CC928E"
bright_white = "#D5CD9D"
bright_yellow = "#D4C196"

[themes.component_style]
block_title = { fg = "Yellow" }
border = { fg = "Blue" }
playback_track = { fg = "Yellow", modifiers = ["Bold"] }
playback_artists = { fg = "Cyan" }
playback_album = { fg = "Magenta" }
playback_metadata = { fg = "BrightBlack" }
playback_progress_bar = { bg = "Blue", fg = "Yellow" }
current_playing = { fg = "Yellow", modifiers = ["Bold"] }
page_desc = { fg = "Cyan", modifiers = ["Bold"] }
table_header = { fg = "Blue" }
selection = { bg = "#363646", fg = "Yellow", modifiers = ["Bold"] }
